alvinwan/timefhuman

.coveragerc, .travis.yml, README.md, setup.py, timefhuman/main.py
- add travis CI
- coveralls code coverage display
- add badges for both
- natural strings for time of day e.g., 'noon'
=> Travis CI, Coveralls

timefhuman/categorize.py
Second merge requests which passes pytest.
=> o'clock fix mark 2

timefhuman/categorize.py, timefhuman/data.py, timefhuman/main.py
It would be awesome if this library could recognize recurrent events such as "5pm on thursdays" - so I added just that. Please note that this is mostly a proof-of-concept and you will likely want to alter the implementation.
=> Add recognition for recurrent events

tests/test_e2e.py, timefhuman/grammar.lark, timefhuman/main.py
support more structured formats (specifically, ISO 8601 and YMD)
=> [dates] Support YMD, ISO

tests/test_e2e.py, timefhuman/grammar.lark, timefhuman/main.py, timefhuman/renderers.py, timefhuman/utils.py
Can now specify 'this', 'next', 'last' (and all synonyms) of months or weeekdays
=> Added date and month modifiers

tests/test_e2e.py, timefhuman/grammar.lark, timefhuman/main.py
- Support times of day like morning, afternoon
- Support datetime names like 'tonight'
=> Support vernacular names for datetimes

README.md, setup.py, tests/test_e2e.py, timefhuman/grammar.lark, timefhuman/main.py, timefhuman/renderers.py, timefhuman/utils.py
- Support absolute weekdays, like `last wed of ...`
- Used relativedelta from dateutil to implement more flexible 'relative dates'
=> Integrate relativedelta, support absolute weekdays

setup.py, timefhuman/renderers.py, timefhuman/utils.py
Backwards compatibility, with version bump
=> Fixes compatibility with python3.8

tests/test_e2e.py, timefhuman/main.py, timefhuman/utils.py
`now` is now populated dynamically each time `timefhuman` is called
=> Fix `now` being populated at start of program

README.md, setup.py
Version bump for next release.
=> [readme] Add new features, version bump

README.md
=> [readme] nits

README.md, tests/test_e2e.py, timefhuman/main.py, timefhuman/renderers.py, timefhuman/utils.py
When `infer_datetimes=True`, force all timedeltas to be datetimes too
=> Apply `infer_datetimes` to timedeltas

README.md, timefhuman/__init__.py, timefhuman/main.py
Modify `timefhuman.DEFAULT_CONFIG` to change global defaults
=> [config] Support global default config

README.md, pyproject.toml, setup.cfg, timefhuman/__init__.py
- expose `__VERSION__` in project root
- updated dev instructions
=> [readme] README update + programatic versioning

README.md, timefhuman/utils.py
just a few extra scrollbars I didn't like
=> [readme] aesthetic changes

README.md, timefhuman/utils.py
Test dates would change if we don't fix the date
=> [readme] Fix README test

README.md
- code https://pytwiddle.com/?id=example%3Adatetime.py
- demo https://pytwiddle.com/app/?id=example%3Adatetime.py
=> [readme] Added PyTwiddle demo

tests/test_e2e.py, timefhuman/main.py
fixes https://github.com/alvinwan/timefhuman/issues/72
=> Support empty string

tests/test_e2e.py, timefhuman/grammar.lark, timefhuman/main.py
ago was not negating direction of timedelta. It is now
=> [transformer] Fixed support for ago

README.md, timefhuman/__init__.py
Quickie to add example to README, bump version for a new release
=> [readme] ago example, version bump
